before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: ghupload
    ldflags:
      - -s -w -X github.com/invit/ghupload/internal/lib/version.Version={{.Version}} -X github.com/invit/ghupload/internal/lib/version.Commit={{.Commit}} -X github.com/invit/ghupload/internal/lib/version.Date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - files:
    - LICENSE
    - README.md
